#!/usr/bin/env python3
"""
INTERCEPTA: VISION ALIGNMENT AUDIT
====================================
Tests EVERY claim in both vision documents against reality.
Not "does the code exist" but "does it DO what the vision says."

Documents tested:
  1. INTERCEPTA_COMPLETE_VISION_v1.0 (Parts 1-12)
  2. INTERCEPTA_Universal_Net_Specification_v1.0 (Parts 1-7)

Run: cd ~/INTERCEPTA/code && python3 vision_alignment_audit.py 2>&1 | tee ../VISION_AUDIT.txt
"""
import pandas as pd
import numpy as np
import json, os, sys, time, glob
from pathlib import Path

BASE = Path(__file__).parent.parent
RESULTS = BASE / 'results'
CODE = BASE / 'code'
DATA = BASE / 'data'

# Counters
met = 0       # Vision requirement met
partial = 0   # Partially met
not_met = 0   # Not met at all
dishonest = 0 # We claimed it was met but it isn't

def MET(req, evidence):
    global met; met += 1
    print(f'  ✓ MET: {req}')
    print(f'    Evidence: {evidence}')

def PARTIAL(req, what_works, what_doesnt):
    global partial; partial += 1
    print(f'  ~ PARTIAL: {req}')
    print(f'    Works: {what_works}')
    print(f'    Doesn\'t: {what_doesnt}')

def NOT_MET(req, why):
    global not_met; not_met += 1
    print(f'  ✗ NOT MET: {req}')
    print(f'    Why: {why}')

def FAKE(req, claim, reality):
    global dishonest; dishonest += 1
    print(f'  🚫 FAKE CLAIM: {req}')
    print(f'    We claimed: {claim}')
    print(f'    Reality: {reality}')

print('='*70)
print('INTERCEPTA VISION ALIGNMENT AUDIT')
print('Every claim in both vision documents tested against reality')
print(f'Started: {time.strftime("%Y-%m-%d %H:%M")}')
print('='*70)

# ═══════════════════════════════════════════════════════════════
# PART 1: THE ONE-SENTENCE VISION
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 1: THE ONE-SENTENCE VISION')
print('"INTERCEPTA discovers novel drug molecules... for ANY disease"')
print('='*70)

NOT_MET('"discovers novel drug molecules that do not yet exist"',
        'We did scaffold hopping (R-group substitution on known scaffolds). '
        'The vision says "diffusion models, transformer-based generative models." '
        'We have no AI generative chemistry. INTC-002 is a medicinal chemistry analog, not a novel entity.')

NOT_MET('"for ANY disease — past, present, or future"',
        'ODE works for mCRPC (6 drugs in PK library). Cannot simulate drugs for other diseases. '
        'Net builder works for 20/20 diseases but ODE simulation breaks for new diseases.')

NOT_MET('"delivers those real drug candidates to pharmaceutical companies"',
        'Pharma package was handwritten by us, not generated by the platform. '
        'No candidate has synthesis route, measured binding, or experimental validation.')

PARTIAL('"so that only clinical trials remain"',
        'Computational predictions exist (ODE, escape routes, statistics)',
        'No candidate is anywhere near clinical trial readiness. '
        'Missing: synthesis, in vitro testing, in vivo PK/PD, toxicology, IND filing.')

# ═══════════════════════════════════════════════════════════════
# PART 3: THE NET APPROACH
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 3: THE NET APPROACH')
print('='*70)

print('\n--- 3.1 Net as knowledge graph ---')
PARTIAL('"literal knowledge graph — every node connected through validated scientific relationships"',
        'STRING (236K edges), KEGG (44K), Open Targets (4.5M), ChEMBL (24K) connected',
        'Layers are in separate CSV files, not a unified queryable graph database. '
        'No graph database (Neo4j/Neptune). Connections require manual pandas merges.')

print('\n--- 3.2 What goes into the net (10 layers specified) ---')
# Test each of the 10 layers from the vision
layers_vision = {
    'Genomic': {'file': 'step2_mutation_frequencies.csv', 'expected': 'mutations, variants, driver vs passenger'},
    'Transcriptomic': {'file': 'velocity_star_latent_time.csv', 'expected': 'scRNA-seq, RNA velocity'},
    'Proteomic': {'file': 'step10_alphafold_structures.csv', 'expected': '3D structures, PTMs, abundance'},
    'Pathway': {'file': 'step5_gene_pathway_map.csv', 'expected': 'signaling pathways, crosstalk'},
    'Network': {'file': 'step4_string_full_interactome.csv', 'expected': 'PPI, regulatory networks'},
    'Cellular': {'file': 'step3_cell_type_assignments.csv', 'expected': 'cell populations'},
    'Chemical': {'file': 'step7_chembl_activities.csv', 'expected': 'compounds with activity'},
    'Clinical': {'file': None, 'expected': 'symptoms, progression, biomarkers, outcomes'},
    'Environmental': {'file': None, 'expected': 'microbiome, immune context, TME'},
    'Selectivity': {'file': 'step6_full_selectivity.csv', 'expected': 'disease-only vs shared nodes'},
}

for layer_name, info in layers_vision.items():
    if info['file'] and (RESULTS / info['file']).exists():
        f = RESULTS / info['file']
        sz = f.stat().st_size
        if sz > 1000:
            if layer_name == 'Proteomic':
                PARTIAL(f'{layer_name} layer: {info["expected"]}',
                        f'File exists ({sz//1024}KB)',
                        'Only AlphaFold structures (20 targets). No PTMs, no abundance, no experimental structures for most targets.')
            elif layer_name == 'Cellular':
                PARTIAL(f'{layer_name} layer: {info["expected"]}',
                        f'Cell type assignments exist for mCRPC scRNA-seq',
                        'Only for one dataset (GSE137829). No Human Cell Atlas integration.')
            else:
                MET(f'{layer_name} layer: {info["expected"]}',
                    f'File: {info["file"]} ({sz//1024}KB)')
        else:
            PARTIAL(f'{layer_name} layer', f'File exists but small ({sz}B)', 'May be incomplete')
    else:
        NOT_MET(f'{layer_name} layer: {info["expected"]}',
                f'File not found or not built. Vision requires: {info["expected"]}')

print('\n--- 3.3 Parallel Scout System (6 scouts) ---')

# Scout 1: Database Search
scout1_path = RESULTS / 'scout1_all_drugs_ranked.csv'
if scout1_path.exists():
    s1 = pd.read_csv(scout1_path)
    PARTIAL('Scout 1: Database search (ChEMBL 2.4M, PubChem 118M, ZINC 750M)',
            f'Searches GDSC (286 drugs). Ranks by ODE-predicted HR.',
            'Only 286 GDSC drugs, not ChEMBL 2.4M or PubChem 118M or ZINC 750M. '
            'Vision says "searches ChEMBL, PubChem, ZINC for disease-specific targets." We search GDSC only.')
else:
    NOT_MET('Scout 1: Database search', 'No ranked drug file found')

# Scout 2: Generative Design
scout2_files = list(RESULTS.glob('scout2_*.json')) + list(RESULTS.glob('scout2_*.csv'))
if scout2_files:
    FAKE('Scout 2: "AI generative models (diffusion, transformer-based)"',
         'We claimed novel molecule generation',
         'We did R-group substitution on known scaffolds. No diffusion model. No transformer. '
         'No graph neural network. The molecules are medicinal chemistry analogs.')
else:
    NOT_MET('Scout 2: Generative Design', 'No scout 2 output files')

# Scout 3: Combination Explorer
escape_path = RESULTS / 'aml_escape_routes_fixed.json'
if escape_path.exists():
    MET('Scout 3: Combination Explorer',
        'Escape route analysis generates rational combinations. '
        'mCRPC: AR→AURKA. AML: 20 drivers with escape routes. 309 combinations.')
else:
    PARTIAL('Scout 3: Combination Explorer', 'Escape routes exist for mCRPC', 'AML file not found')

# Scout 4: Network Perturbation
NOT_MET('Scout 4: "Simulates what happens to entire disease net when each candidate is applied"',
        '3 attempts (heat diffusion, Boolean, expression-filtered). ALL produced 0 compensators. '
        'Redefined as "data-driven perturbation" using BeatAML. '
        'Vision says simulate ENTIRE NET perturbation. We cannot do this.')

# Scout 5: Evolutionary Optimizer
scout5_files = list(RESULTS.glob('scout5_*'))
if scout5_files:
    PARTIAL('Scout 5: Evolutionary Optimizer',
            '18 INTC-002 variants generated',
            'Variants not docked. No selectivity optimization achieved. '
            'INTC-002 still has no AURKA selectivity.')
else:
    NOT_MET('Scout 5: Evolutionary Optimizer', 'No variants generated')

# Scout 6: Cross-Disease Transfer
NOT_MET('Scout 6: "Checks if molecules for previous diseases might be repurposed"',
        'Found 3 cross-disease candidates by name matching. '
        'Vision says systematic evaluation based on shared net nodes. '
        'We did string matching on drug names, not net-based transfer.')

print('\n--- 3.3 "All scouts share information" ---')
NOT_MET('"Insights from Scout 4 improve which molecules Scout 2 generates"',
        'Scouts are independent scripts that do not communicate. '
        'No shared data structure. No bidirectional insight sharing. '
        'Each scout runs in isolation.')

# ═══════════════════════════════════════════════════════════════
# PART 4: THE FIVE-STAGE PIPELINE
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 4: FIVE-STAGE PIPELINE')
print('='*70)

# Stage 1
print('\n--- Stage 1: Build Complete Disease Net ---')
PARTIAL('Stage 1: "Automated construction of complete knowledge graph for target disease"',
        'Disease net builder works for 20/20 diseases. Queries Open Targets + STRING + KEGG.',
        'Not "complete" — missing clinical outcomes, microbiome, epigenome primary data. '
        'No "completeness score, consistency score, coverage score" as vision specifies.')

# Stage 2
print('\n--- Stage 2: Map Vulnerability Points and Selectivity ---')
PARTIAL('Stage 2: "Automated identification of targetable nodes"',
        'GTEx selectivity ratios exist for 54K genes. Escape routes identified for mCRPC and AML.',
        'No automated "selectivity map" that classifies every node as disease-specific vs shared. '
        '"Escape route" identification requires human judgment for drug selection.')

# Stage 3
print('\n--- Stage 3: Deploy Parallel Scouts ---')
NOT_MET('Stage 3: "All six scout types run simultaneously"',
        'Scouts are separate Python scripts run manually one at a time. '
        'No parallel execution. No shared insight mechanism.')

# Stage 4
print('\n--- Stage 4: Full In Silico Simulation Stack ---')

sim_layers = {
    'Layer A: Molecular Docking': {
        'vision': 'AutoDock Vina, binding affinity + selectivity ratio > 10:1',
        'reality': 'Vina works for AURKA (PDB 4J8M). Protocol validated. But only tested for 1 target.',
        'status': 'PARTIAL',
    },
    'Layer B: Cell Population Sensitivity': {
        'vision': 'KAALCURA per cell population. Kills sensitive + resistant + spares healthy.',
        'reality': 'KAALCURA computes per-bin sensitivity (286 drugs x 20 bins). No per-PATIENT population.',
        'status': 'PARTIAL',
    },
    'Layer C: Disease Dynamics': {
        'vision': 'Two-population ODE + PK/PD. 5-year simulation. No resistant cell resurgence.',
        'reality': 'Phenotype ODE works for mCRPC docetaxel/enza. AML 3-comp validated for untreated.',
        'status': 'PARTIAL',
    },
    'Layer D: Combination Synergy': {
        'vision': 'ZIP + Bliss + Loewe + HSA consensus. No significant antagonism.',
        'reality': 'Synergy math implemented and tested on SYNTHETIC data only. Not validated on NCI-ALMANAC.',
        'status': 'PARTIAL',
    },
    'Layer E: Safety and ADMET': {
        'vision': 'SwissADME, pkCSM, ADMET-AI. Passes Lipinski + ADMET + organ toxicity.',
        'reality': 'RDKit Lipinski + rule-based CYP/hERG flags. No SwissADME API. No pkCSM. No ADMET-AI.',
        'status': 'PARTIAL',
    },
    'Layer F: Synthesizability': {
        'vision': 'ASKCOS retrosynthesis. Retrosynthetic route exists. Complexity acceptable.',
        'reality': 'SA_Score from RDKit only. No ASKCOS. No actual synthesis routes.',
        'status': 'NOT_MET',
    },
}

for layer, info in sim_layers.items():
    if info['status'] == 'PARTIAL':
        PARTIAL(f'{layer}: {info["vision"][:60]}',
                info['reality'][:80],
                f'Vision requires: {info["vision"][:60]}')
    else:
        NOT_MET(f'{layer}: {info["vision"][:60]}',
                info['reality'])

# Stage 5
print('\n--- Stage 5: Multi-Objective Ranking and Delivery ---')

# Check ranking dimensions
FAKE('Stage 5: "Multi-objective score across efficacy/selectivity/safety/resistance/novelty/synth"',
     'Pareto ranking exists with all 6 dimensions scored',
     'Dimension scores (efficacy=75, selectivity=80, etc.) were TYPED BY US. '
     'No computation generates these scores. The ranking reflects our judgment, not pipeline output.')

# Check delivery package
vision_delivery = [
    'Complete molecular structure (SMILES + 3D)',
    'Mechanism of action explanation',
    'Predicted clinical outcomes with confidence intervals',
    'Full safety profile',
    'Synthesis route',
    'Novelty confirmation from ClinicalTrials.gov',
    'Comparison vs standard of care',
    'Suggested clinical trial design',
]

pkg_path = RESULTS / 'pharma_deliverable_enza_alis.json'
if pkg_path.exists():
    with open(pkg_path) as f:
        pkg = json.load(f)
    
    for item in vision_delivery:
        # Check if the item has COMPUTED content (not human-written)
        key_words = item.lower().split()[:3]
        matching_keys = [k for k in pkg.keys() if any(w in k.lower() for w in key_words)]
        
        if matching_keys:
            val = pkg[matching_keys[0]]
            val_str = json.dumps(val) if isinstance(val, dict) else str(val)
            
            if len(val_str) > 100:
                # But is it computed or handwritten?
                if item == 'Complete molecular structure (SMILES + 3D)':
                    MET(f'Delivery: {item}', 'SMILES from published molecules. Real.')
                elif item == 'Novelty confirmation from ClinicalTrials.gov':
                    MET(f'Delivery: {item}', 'ClinicalTrials.gov API queried. Real.')
                elif 'confidence intervals' in item:
                    has_ci = 'CI' in val_str or 'ci' in val_str.lower()
                    if has_ci:
                        PARTIAL(f'Delivery: {item}',
                                'Bootstrap CI exists for docetaxel HR',
                                'Combination prediction lacks CI. Escape route ODE has no uncertainty quantification.')
                    else:
                        NOT_MET(f'Delivery: {item}', 'No confidence intervals in outcomes')
                else:
                    FAKE(f'Delivery: {item}',
                         f'Content exists ({len(val_str)} chars)',
                         'Content was WRITTEN BY US, not generated by pipeline. '
                         'A human typed the mechanism, safety, trial design text.')
            else:
                NOT_MET(f'Delivery: {item}', f'Content too thin ({len(val_str)} chars)')
        else:
            NOT_MET(f'Delivery: {item}', 'Item not found in package')

# ═══════════════════════════════════════════════════════════════
# PART 5: UNIQUE SCIENTIFIC CONTRIBUTIONS
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 5: UNIQUE SCIENTIFIC CONTRIBUTIONS')
print('='*70)

# 5.1 RNA Velocity Time Machine
print('\n--- 5.1 RNA Velocity Time Machine ---')
vel_path = RESULTS / 'velocity_star_latent_time.csv'
if vel_path.exists():
    PARTIAL('"Detect pre-resistant population on Day 1 using RNA velocity"',
            '46,235 cells with latent time computed. Bimodal distribution (bins 2 and 9). '
            'Late-state cells concentrated in 2 of 13 clusters.',
            'Only tested on one dataset (GSE137829 mCRPC). Not validated prospectively. '
            'Not connected to KAALCURA per-cluster analysis in automated way. '
            'Vision says "applied to any patient biopsy." We tested one public dataset.')
else:
    NOT_MET('RNA Velocity Time Machine', 'No velocity data found')

# 5.2 KAALCURA
print('\n--- 5.2 KAALCURA Per-Population Biological Axes ---')
kaal_path = RESULTS / 'kaalcura_per_bin.csv'
if kaal_path.exists():
    PARTIAL('"Applied independently to each cell cluster — not bulk average"',
            'KAALCURA computed per 20 resistance bins (R_prolif, R_emt, R_ddr). AUROC 0.638.',
            'Applied to bins of a SIMULATED resistance gradient, not actual cell clusters from scRNA-seq. '
            'Vision says "independently to the sensitive cluster and resistant cluster identified by RNA velocity." '
            'We compute axes per bin of the phenotype model, not per real patient cell cluster.')
else:
    NOT_MET('KAALCURA per-population', 'No per-bin data found')

# 5.3 Two-Population ODE
print('\n--- 5.3 Two-Population ODE Simulation ---')
PARTIAL('"Sensitive cells and resistant cells modeled as separate mathematical compartments"',
        'mCRPC: 20-bin phenotype ODE + 4-state escape route ODE. '
        'AML: 3-compartment (blast+LSC+normal) + 4-compartment (with resistance). '
        'Docetaxel HR=0.69, Enza PFS=18.6mo validated.',
        'Vision says "validated against CHAARTED, LATITUDE, PROfound, PROpel, TALAPRO-2." '
        'We validated against TAX-327 and PREVAIL only. 3 of 5 specified trials not tested.')

# ═══════════════════════════════════════════════════════════════
# PART 7: DISEASE EXPANSION
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 7: DISEASE EXPANSION (7 rounds)')
print('='*70)

expansion = {
    'Round 1: mCRPC': 'PARTIAL — ODE validated for doc/enza. Escape routes found. No complete deliverable.',
    'Round 2: AML': 'PARTIAL — Net built (4558 genes). BeatAML statistics. ODE validated for untreated. No drug ranking through ODE.',
    'Round 3: NSCLC': 'NOT MET — Disease net exists (498 genes). No NSCLC-specific analysis.',
    'Round 4: PDAC': 'NOT MET — Disease net exists (498 genes). No PDAC-specific analysis.',
    'Round 5: Alzheimer': 'NOT MET — Disease net exists (498 genes). No Alzheimer-specific analysis.',
    'Round 6: TB': 'NOT MET — Disease net exists (211 genes). No TB-specific analysis.',
    'Round 7+: All rare diseases': 'NOT MET — Disease net builder works for 20/20 diseases. No analysis beyond net.',
}

for round_name, status in expansion.items():
    if status.startswith('PARTIAL'):
        PARTIAL(round_name, status.split('—')[1], 'Not complete')
    else:
        NOT_MET(round_name, status.split('—')[1])

# ═══════════════════════════════════════════════════════════════
# PART 8: WHAT MAKES INTERCEPTA DIFFERENT (comparison claims)
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 8: DIFFERENTIATION CLAIMS')
print('='*70)

diff_claims = {
    '"Uses RNA velocity for proactive resistance targeting"': {
        'status': 'PARTIAL',
        'reality': 'RNA velocity computed for one dataset. Not integrated into drug selection pipeline.',
    },
    '"Generates novel molecules"': {
        'status': 'FAKE',
        'claim': 'AI generative chemistry',
        'reality': 'Scaffold hopping (R-group substitution). No AI model.',
    },
    '"Models two-population dynamics"': {
        'status': 'MET',
        'reality': 'Phenotype ODE (20-bin) + escape route ODE (4-state). Both validated.',
    },
    '"Ranks combination permutations exhaustively"': {
        'status': 'PARTIAL',
        'reality': 'Escape routes generate combinations. But ranking uses human-assigned scores, not computed.',
    },
    '"Open science — all data sources public"': {
        'status': 'MET',
        'reality': 'All 9 data sources are public databases. Verified.',
    },
    '"Healthy cell protection from the beginning"': {
        'status': 'PARTIAL',
        'reality': 'GTEx selectivity ratios exist. But not enforced as hard filter in pipeline.',
    },
}

for claim, info in diff_claims.items():
    if info['status'] == 'MET':
        MET(claim, info['reality'])
    elif info['status'] == 'PARTIAL':
        PARTIAL(claim, info['reality'], 'Not fully implemented')
    elif info['status'] == 'FAKE':
        FAKE(claim, info['claim'], info['reality'])
    else:
        NOT_MET(claim, info['reality'])

# ═══════════════════════════════════════════════════════════════
# PART 10: TECHNOLOGY ARCHITECTURE (from vision)
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION PART 10: TECHNOLOGY STACK')
print('='*70)

tech_stack = {
    'AlphaFold structures': ('PARTIAL', '20 targets downloaded. Not all drug targets covered.'),
    'ChEMBL/PubChem/ZINC searches': ('PARTIAL', 'ChEMBL queried (24K). PubChem and ZINC NOT queried.'),
    'AutoDock Vina docking': ('MET', 'Vina installed, protocol validated on PDB 4J8M.'),
    'Generative chemistry (DDPM/GNN)': ('NOT_MET', 'No diffusion model. No GNN. Scaffold hopping only.'),
    'SwissADME/pkCSM ADMET': ('PARTIAL', 'RDKit Lipinski + rule-based. No SwissADME/pkCSM API.'),
    'ASKCOS retrosynthesis': ('NOT_MET', 'Not built. SA_Score only.'),
    'KEGG/Reactome pathways': ('MET', '9,319 genes, 44,686 edges from KEGG API.'),
    'STRING protein network': ('MET', '236,837 edges from STRING v12 bulk download.'),
    'scVelo RNA velocity': ('MET', 'Dynamical mode velocity computed for 46K cells.'),
    'KAALCURA axes': ('MET', 'R_prolif/R_emt/R_ddr. AUROC 0.638. Residualized.'),
    'ODE simulation + PK/PD': ('PARTIAL', 'Works for 6 drugs. Cannot simulate arbitrary compounds.'),
    'Synergy scoring (ZIP/Bliss/Loewe/HSA)': ('PARTIAL', 'Math correct. Tested on synthetic data only.'),
    'Pareto ranking': ('FAKE — scores typed, not computed', 'Algorithm correct but inputs are human-assigned.'),
    'ClinicalTrials.gov novelty': ('MET', 'API queried for enza+alisertib. Returns 0 trials.'),
}

for tool, (status, detail) in tech_stack.items():
    if status == 'MET':
        MET(f'Tech: {tool}', detail)
    elif status == 'PARTIAL':
        PARTIAL(f'Tech: {tool}', detail, 'Not fully implemented')
    elif status.startswith('FAKE'):
        FAKE(f'Tech: {tool}', 'Claimed as working', detail)
    else:
        NOT_MET(f'Tech: {tool}', detail)

# ═══════════════════════════════════════════════════════════════
# UNIVERSAL NET SPEC: 15 LAYERS
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('UNIVERSAL NET SPEC: 15 LAYERS')
print('='*70)

net_layers = {
    'L1 Complete Human Genome': ('MET', 'GDSC 25,861 genes + SU2C 13,512 genes + Open Targets 26,288 diseases.'),
    'L2 Complete Transcriptome': ('PARTIAL', 'One mCRPC scRNA-seq dataset. Not GTEx bulk + HCA single-cell for all tissues.'),
    'L3 Complete Proteome': ('PARTIAL', '20 AlphaFold structures. Vision says "every human protein structure."'),
    'L4 Complete Interactome': ('MET', 'STRING v12: 236,837 edges, 16,194 genes. High confidence.'),
    'L5 Complete Pathway Map': ('MET', 'KEGG 9,319 genes + Reactome. 44,686 edges.'),
    'L6 Cell Type Atlas': ('PARTIAL', 'One dataset cell types. No Human Cell Atlas / Tabula Sapiens.'),
    'L7 Complete Pharmacome': ('PARTIAL', 'ChEMBL 24K activities + GDSC 286 drugs. Not ZINC 750M.'),
    'L8 Complete Metabolome': ('MET', 'Human-GEM 50,323 edges. Cofactors removed.'),
    'L9 Complete Disease Map': ('MET', 'Open Targets 4.5M associations, 26,288 diseases.'),
    'L10 Immune System Map': ('PARTIAL', 'DICE 15 cell types. No CIBERSORTx deconvolution. No TCIA.'),
    'L11 Human Microbiome': ('PARTIAL', '1,069 proxy edges from STRING. No HMP primary sequencing data.'),
    'L12 Complete Epigenome': ('PARTIAL', '2,476 proxy edges from STRING. No ENCODE ChIP-seq. No Roadmap bisulfite.'),
    'L13 Human Anatomy': ('PARTIAL', 'GTEx tau specificity. No HuBMAP spatial. No Allen Brain Atlas.'),
    'L14 Pathogen Database': ('PARTIAL', 'Open Targets 642 infectious diseases. CARD downloaded. Not parsed.'),
    'L15 Selectivity Layer': ('MET', 'GTEx 54,592 genes x 54 tissues. Prostate ratios computed.'),
}

for layer, (status, detail) in net_layers.items():
    if status == 'MET':
        MET(f'Net {layer}', detail)
    elif status == 'PARTIAL':
        PARTIAL(f'Net {layer}', detail, 'Vision requires "complete." We have partial.')
    else:
        NOT_MET(f'Net {layer}', detail)

# ═══════════════════════════════════════════════════════════════
# UNIVERSAL NET SPEC: Part 3 — How layers connect
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('UNIVERSAL NET SPEC: LAYER CONNECTIVITY')
print('"Every entity can connect to any other through validated scientific relationships"')
print('='*70)

NOT_MET('"One unified knowledge graph where every entity connects to any other"',
        'Data is in separate CSV/JSON files. No unified graph database. '
        'To trace BRCA2 → protein structure → pathway → drug → metabolite requires '
        'loading 5 separate files and manual pandas merges. '
        'Vision says "a single queryable system." We have separate files.')

# Test: can we trace the BRCA2 example from the vision?
print('\n  LIVE TEST: Trace BRCA2 through all layers (vision example)')
brca2_trace = {}

# Layer 1: Gene
brca2_trace['gene'] = 'BRCA2' # trivial

# Layer 4: Interactions
if (RESULTS / 'step4_string_full_interactome.csv').exists():
    string = pd.read_csv(RESULTS / 'step4_string_full_interactome.csv')
    brca2_partners = string[(string['gene_a']=='BRCA2') | (string['gene_b']=='BRCA2')]
    brca2_trace['interactions'] = len(brca2_partners)
    print(f'    L4 Interactions: {len(brca2_partners)} partners')

# Layer 5: Pathways
if (RESULTS / 'step5_gene_pathway_map.csv').exists():
    pw = pd.read_csv(RESULTS / 'step5_gene_pathway_map.csv')
    brca2_pw = pw[pw['gene']=='BRCA2']
    brca2_trace['pathways'] = len(brca2_pw)
    print(f'    L5 Pathways: {len(brca2_pw)}')

# Layer 7: Compounds
if (RESULTS / 'step7_chembl_activities.csv').exists():
    chembl = pd.read_csv(RESULTS / 'step7_chembl_activities.csv')
    tc = [c for c in chembl.columns if 'target' in c.lower() or 'gene' in c.lower()][0]
    brca2_compounds = chembl[chembl[tc]=='BRCA2']
    brca2_trace['compounds'] = len(brca2_compounds)
    print(f'    L7 Compounds: {len(brca2_compounds)}')

# Layer 8: Metabolites
if (RESULTS / 'step9_metabolome_gene_edges.csv').exists():
    metab = pd.read_csv(RESULTS / 'step9_metabolome_gene_edges.csv')
    brca2_metab = metab[metab['gene_symbol']=='BRCA2']
    brca2_trace['metabolites'] = len(brca2_metab)
    print(f'    L8 Metabolites: {len(brca2_metab)}')

# Layer 9: Diseases
if (RESULTS / 'step8_gene_disease_associations.parquet').exists():
    import pyarrow.parquet as pq
    ot = pq.read_table(RESULTS / 'step8_gene_disease_associations.parquet').to_pandas()
    gc = [c for c in ot.columns if c in ['gene','targetId']][0]
    brca2_diseases = ot[ot[gc]=='BRCA2']
    brca2_trace['diseases'] = len(brca2_diseases)
    print(f'    L9 Diseases: {len(brca2_diseases)}')

# Layer 15: Selectivity
if (RESULTS / 'step6_full_selectivity.csv').exists():
    gtex = pd.read_csv(RESULTS / 'step6_full_selectivity.csv', index_col=0)
    if 'BRCA2' in gtex.index:
        brca2_trace['selectivity'] = True
        print(f'    L15 Selectivity: prostate_tpm={gtex.loc["BRCA2","prostate_tpm"]:.0f}')

layers_connected = sum(1 for v in brca2_trace.values() if v and v != 0)
print(f'    BRCA2 connected to {layers_connected} layers out of 15')

if layers_connected >= 5:
    PARTIAL('BRCA2 multi-layer trace',
            f'Connected to {layers_connected} layers',
            'Requires manual code to trace. Not a single query against unified graph.')
else:
    NOT_MET('BRCA2 multi-layer trace',
            f'Only connected to {layers_connected} layers')

# ═══════════════════════════════════════════════════════════════
# NOVEL TECHNOLOGY (Part 7 of Universal Net Spec)
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('NOVEL TECHNOLOGY REQUIREMENTS')
print('='*70)

novel_tech = {
    'Multi-scale graph neural networks': 'NOT BUILT. No GNN code exists.',
    'Temporal knowledge graphs': 'NOT BUILT. All our data is static snapshots.',
    'Causal inference on biological graphs': 'NOT BUILT. All edges are correlational.',
    'Federated learning for clinical data': 'NOT BUILT. No federated architecture.',
    'Net-constrained generative chemistry': 'NOT BUILT. Scaffold hopping only.',
}

for tech, status in novel_tech.items():
    NOT_MET(f'Novel Tech: {tech}', status)

# ═══════════════════════════════════════════════════════════════
# FINAL SCORECARD
# ═══════════════════════════════════════════════════════════════
print('\n' + '='*70)
print('VISION ALIGNMENT FINAL SCORECARD')
print('='*70)

total = met + partial + not_met + dishonest
print(f'\n  TOTAL VISION REQUIREMENTS TESTED: {total}')
print(f'  ✓ MET:        {met} ({met/total*100:.0f}%)')
print(f'  ~ PARTIAL:    {partial} ({partial/total*100:.0f}%)')
print(f'  ✗ NOT MET:    {not_met} ({not_met/total*100:.0f}%)')
print(f'  🚫 FAKE CLAIM: {dishonest} ({dishonest/total*100:.0f}%)')

print(f'\n  HONEST VISION ALIGNMENT: {met/total*100:.0f}% fully met')
print(f'  WITH PARTIAL CREDIT: {(met + 0.5*partial)/total*100:.0f}%')

print(f'\n{"="*70}')
print('WHAT THE VISION PROMISED vs WHAT EXISTS')
print('='*70)
print(f"""
  VISION: "Universal computational engine for ANY disease"
  REALITY: Works partially for 2 diseases (mCRPC, AML). 
           Net builder works for 20+ diseases but ODE/ranking only for mCRPC.

  VISION: "Discovers novel drug molecules that do not yet exist"
  REALITY: Scaffold hopping on known inhibitors. No AI generative chemistry.

  VISION: "Delivers real drug candidates ready for clinical trials"
  REALITY: Pharma package was handwritten. No candidate has synthesis route
           or experimental validation.

  VISION: "Net approach — every route explored simultaneously"
  REALITY: Scouts run independently, manually, one at a time.
           No parallel execution or information sharing.

  VISION: "Self-improving system that gets faster with every disease"
  REALITY: No feedback loop. No active learning. Each disease built from scratch.

  WHAT IS GENUINELY VALUABLE:
  - Data infrastructure: 9 GB public data, correctly parsed
  - Disease net builder: works for 20/20 diseases in <1 second
  - ODE predictions: docetaxel HR, enzalutamide PFS match clinical data
  - Escape route discovery: AR→AURKA, EGFR→MET, FLT3 escapes — real biology
  - Statistical analysis: NPM1+cabozantinib p=2.9e-12 — real finding
  - Bootstrap validation: clinical HR inside confidence interval
  - Honest science: p38 MAPK retracted, INTC-002 selectivity failure caught
""")

# Save
results = {
    'date': time.strftime('%Y-%m-%d %H:%M'),
    'total': total, 'met': met, 'partial': partial, 
    'not_met': not_met, 'dishonest': dishonest,
    'alignment_pct': round(met/total*100, 1),
    'with_partial_pct': round((met + 0.5*partial)/total*100, 1),
}
with open(RESULTS / 'vision_alignment_audit.json', 'w') as f:
    json.dump(results, f, indent=2)
print(f'Saved: results/vision_alignment_audit.json')
